# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: groupin_development
  username: root
  password: desidime@123
  pool: 5

development:
    adapter: postgresql
    host: localhost
    database: groupin_development
    username: desidime
    password: desidime123

production:
  adapter: postgresql
  database: groupin_production
  username: desidime
  password: desidime123
  reconnect: true


